# devices/matrix1000_names.py — Matrix-1000 factory patch names (banks 0-9,
# 100 each = patch number 0-999). Source: Matrix-1000 patchbook
# (larslentzaudio.wordpress.com), parsed 2026-08-26. These are the KNOWN
# factory sound-set names; a unit whose memory holds generic "BNKn: nn"
# names still shows these as the reference for each slot.

FACTORY_PATCH_NAMES = [
    'totohorn', '1000strg', 'mooog_b', 'ezybrass', 'synth',
    'mibes', 'chunk', 'mindsear', 'castillo', 'destroy+',
    'big pik', 'm-choir', 'stringme', ')liquid(', 'pno-elec',
    'bed trak', 'stellar', 'syncage', 'shivers', '+ zeta +',
    'steeldr.', 'taurus', 'powrsolo', 'interstl', 'reztful',
    'watrlng', 'beels', 'likethis', 'nthenews', 'soft mix',
    'obxa-a7', 'breath', 'mutrono', 'slowater', 'haunting',
    'flanged', 'tension', 'echotron', 'pirates!', 'ep swep',
    "dejavue'", 'drama', 'violince', 'bounce', "sagan'z",
    'ob lead', 'feedgit', 'sample', 'tinypian', 'galactic',
    'dou ciel', 'wa clav', 'dreamer', 'xa str', 'church',
    'kidding?', 'thunder', 'echowurl', 'blabinet', 'strungs',
    'african', 'b3+lslie', 'chimes', 'dipian', 'laz harp',
    'smthsq2', 'trumpets', 'papano 4', 'wipbass', 'lyle-8va',
    'sitar', 'viogitar', 'goliath', 'anaxylo', 'fury0',
    'synluth', 'chamber', 'spatbrs', 'etheree', 'tbrazz',
    'noble', 'flextone', 'greezy2', 'arppegt', 'jump ies',
    'hardvark', 'sweetsky', 'shimring', 'timbows', 'gallop',
    'prelude1', 'growlbrz', 'clickorg', 'preslez1', 'lyle',
    'arcangel', 'benshimr', 'lushness', 'noistrng', 'sopipes',
    'papano 4', 'wurly 2', 'totohorn', 'agresorn', 'string s',
    'odx 7', 'jump ies', 'profit', 'voices', "sagan'z",
    'pa ano 5', 'monster', 'genviv', 'clavinet', 'stringer',
    'simonisk', 'hotbodom', 'xtasy', ')liquid(', 'bed trak',
    'roads', 'echowurl', 'polyphon', 'dreamer', 'histrung',
    "dejavue'", 'wet baz', 'pipe', 'octavia', 'ob-strgs',
    'kawhy', 'jocko', 'flutes', 'atypical', 'bow viol',
    'vertabra', 'slap 1', 'p.organ5', 'octahorn', 'lushness',
    '12"gitar', 'stand up', "bert's b", 'brass-11', 'stringme',
    'leed-2', 'ow bass', 'organ-1', 'hornisk', 'string-1',
    'caripso', 'faz bass', 'organ-2', 'phasepad', 'string 2',
    'bata', 'bass syn', 'syncage*', 'digihorn', 'cello',
    'glassvox', 'fret not', 'organism', 'limuidz', 'stranger',
    'papano 7', 'wow bass', 'p.organ4', 'melohorn', 'leed-1',
    'tinypian', 'slap 2', 'forests', 'honoclab', 'string 7',
    'velsync*', 'rainecho', 'organ 9', 'brazz', 'accord',
    'digpiano', 'tenor', 'stortgan', 'viogitar', 'strunget',
    'birdland', 'metal-1', 'metal-8', 'funk art', 'metal-13',
    'vibes', 'string 6', 'strngrez', 'sings', 'timbows',
    'whistle', 'oberhorn', 'toots ?', 'fireball', 'smplthis',
    'obxa-11', 'obxa-12', 'obxa-a2', 'obxa-a7', 'obxa-b7',
    'obxa-b8', 'obxa-c2', 'obxa-c4', 'obxa-c6', 'obxa-c7',
    'obxa-c8', 'obxa-d2', 'obxa-d3', 'obxa-d4', 'obxa-d5',
    'obxa-d6', 'obxa-d7', 'obxa-d8', 'obxa-9"', 'obca-re',
    'obxjmp', "*'angel", '+ zeta +', '1984swp6', 'waves',
    '80ms ddl', 'synth', 'aerial', 'alienswp', 'ambiance',
    'anaftst*', 'anaharp', 'analog b', 'anaxylo*', 'angels',
    'apollo', 'arcangel', 'argex-1', 'argon7', 'atypical',
    'aw why ?', 'benshimr', 'beowcomp', 'billy', 'blaszz',
    'blockout', 'boeptyn*', 'bottles', 'bounce*', 'brassvox',
    'brillant', 'broadway', 'bs etak*', 'burnhous', 'camera 1',
    'chime 1', 'chime 2', 'chunk', 'cmi high', 'coeaur 1',
    'colony 9', 'cryslake', 'cs-80', 'deacon', "dejavue'",
    'didier', 'distance', 'dmachine', 'dreamer', 'dreemer',
    'ducktime', 'dunk it', 'e n o 1', 'echosyn', 'echotron',
    'egypt', 'ep swep*', 'epch+brz', 'epdstrt*', 'esq-1',
    'etheree', 'fake ddl', 'fifths', 'floatong', 'flpflop*',
    'fly to', 'fm bass', 'fundo', '*funk art', 'funkay',
    'furyo', 'fweep', 's.1', 'galactic', 'gallop *',
    'geniveev', 'genviv', 'genviv*', 'girlswep', 'good bed',
    'goodtime', 'grotto', 'hackett', 'halo', 'harmovox',
    'harpoon', 'heli-in', 'hometown', 'interstl', 'itsonice',
    'jazzquit', 'jm jarre', "john b's", 'kcepmax*', 'kcepsaw*',
    'kchsync*', 'kirkland', 'ldsubhrm', 'likethis', 'lstlaugh',
    "lun'air", 'm-choir', 'magical', 'marin', 'matmodul',
    'matrix 1', 'matrix 2', 'metaboad', 'metabrd', 'mindsear',
    'monster', 'mr kyrie', 'musicbox', 'nautilus', 'new vox',
    'newsound', 'nightpad', 'ob sweep', 'ob vox*', 'ob-intro',
    'obxa-b2', 'obxa-b4', 'octavia', 'open air', 'ordinary',
    'p chord', 'p-pluck', 'pad', 'perc s', 'phase 5',
    'phasecho', 'picky', 'pipestr', 'pn/fmswp', 'polchoir',
    'power', 'prophet1', 'prophet5', 'prophetv', 'psylitis',
    'rez*puls', 'reztful', 'sample', 'saturn', 'science',
    'scritti+', 'secrets', 'sensit 2', 'sensitiv', 'sequinox',
    'shankar', 'shimmer', 'shimring', 'shivers', 'skrchtn*',
    'sktsoky*', 'sky high', 'skyvoice', 'slapbach', 'slidstg',
    'slow cry', 'slowater', 'smthsq2*', 'soft mix', 'soundpad',
    'soundtr[', 'space', 'space/co', 'sparkles', 'splash 1',
    'stellar*', 'stugrowl', 'styx', 'submarin', 'sunday',
    'sussudio', 'swepcord', 'swrleko*', 'syn box*', 'syncage*',
    'totohorn', 'obxa-13', 'obxa-a1', 'obxa-b1', 'obxa-c1',
    'obxa-d1', '6r brass', 'agresorn', 'alaska', 'ana hit*',
    'anasutl*', "b'ari/s2", 'b/d-ana*', 'bagpipes', 'barisax',
    'basclrnt', 'bassclar', 'bassoon', 'bendhorn', 'bigbra$$',
    'bones', 'brasramp', 'btrassvox', 'brassy', 'brazen',
    'brecher', 'brth flt', 'brutus', 'brziviv*', 'buchann*',
    'buzreed', 'chroma-s', 'clarinet', 'crazhorn', 'cs-80',
    'cuivre((', 'dblreed*', 'eastreed', 'edgy', 'ensembl*',
    'europe', 'ewf horn', 'ezybrass', 'factory', 'fifths',
    'flglhorn', 'floot', 'flugelhn', 'flugle', 'flute',
    'flute tr', 'flute.', 'flutes', 'flutey', 'flux',
    'fm braz', 'fm delay', 'fr.horn', 'fnrchrn*', 'fthweel*',
    'fue.japn', 'fusion', 'fweep', 'gabriel', 'go bed',
    'goliath', "horn'em", 'horn-1', 'hornens', 'hornfall',
    'hornsas', 'horny', 'hrnshake', 'j hammer', 'jtullflt',
    'jubilee', 'klarynet', 'korghorn', 'lyricon', 'matrone',
    'melfaze*', 'melohorn', 'metheny5', 'mutetrpt', 'ob brass',
    'ob-8', 'oberhorn', 'oboe', 'oct.brs', 'octaflut',
    'octahorn', 'orient', 'pedswp*', 'peg-brs', 'pyrmflt*',
    'rahoool*', 'recorder', 'relvelho', 'richcord', 'roman',
    'sexafoam', 'slo hrn', 'sopipes', 'spatbrs*', 'squardou',
    'stab', 'stab-brs', 'steps 2.', 'stuflute', 'swrlybrd',
    'syn sax*', 'synbass', 'synbone', 'synbrss*', 'synhorn',
    'tbrazz', 'tenor', 'totoal', 'touch+go', 'trillflt',
    'trmbone*', 'trombone', 'trumpets', 'trupt-eu', '* 99 *',
    'tuba 2', 'obxa-a8', 'elead*', 'bdth-2', 'birdy',
    'breckerl', 'castillo', 'chick', 'destroy+', 'digrunge',
    'dragon-3', 'dxindian', 'feedbak6', 'feedbak8', 'feedgit',
    'fifth i%', 'fifthlix', 'glasleed', 'growlbrs', 'h-lead',
    'hileed 6', 'j hammer', 'jakoleed', 'jan lead', 'jazz',
    "jimy'srg", 'kc lead*', 'kidding?', 'lead+prt', 'lead-1',
    'lead-3', 'leed-1', 'leed-2', 'lyle 2', 'lyle 3 m',
    'metheney', 'metlsolo', 'milescom', 'minimogg', 'minimoog',
    'monostrg', 'nasty', 'ob lead*', 'osc sync', 'panfloet',
    'pinklead', 'powrsolo', 'prsslide', 'quincy', 'recorder',
    'rezlead*', 'sawlead*', 'sitar', 'smooth', 'smuthsq*',
    'solo', 'solodarm', 'soloprof', 'solosync', 'solow*',
    'sopipes', 'spitleed', 'sqareled', 'stuvib', 'susguit',
    'snthe 5', 'uksolo', 'unibass', 'uniwave', 'wakemans',
    'weirdprc', 'whistler', 'winand 1', "xa'solo", "zaw'qart",
    'obxa-10', 'obxa-14', 'obxa-a3', 'obxa-b3', 'obxa-b6',
    'obxa-c3', 'obxa', 'obxa-6', '(arco)01', "*'canopy",
    '1000strg', 'top', '2000strg', 'agitato*', 'all love',
    'alt84top', 'bed trak', 'blacseam', 'bow it', 'bow viol',
    'cello', 'chamber', 'chillo', 'classika', 'concert',
    'deepcave', 'depths', 'dlaystr*', 'donstrig', "dou'ciel",
    'dungeon', 'dynasty', 'e.violin', 'famus*ob', 'forests',
    'granules', 'great"ob', 'harmonic', 'icy-chrd', 'indnstrg',
    'lowstrng', 'loyal', 'lushness', 'lyle-8va', 'mello=14',
    'mksings', 'money $$', 'mutedstr', 'mzstring', 'noble',
    'noistgs', 'ob a3pd*', 'ob-str1n', 'ob-strgs', 'obstring',
    'obxa-a6', 'ocarina', 'ochestry', 'openstrg', 'orch*',
    'orient', 'pitz str', 'pizz^+p2', 'planet p', 'polstrg2',
    'prohet-5', 'prophet5', 'rid zep', 'royal ph', 'rp strg5',
    "secrets'", 'sharpbow', 'shift', 'shrtstrg', 'sings',
    'slidstg', 'slow bow', 'slow cry', 'smash', 'solemn',
    'solemnis', 'solo', 'soundtr', 'soundtrk', 'soundtr[',
    'srtrongs', 'stand up', 'str end*', 'str-8va', 'stranger',
    'streeng', 'streengs', 'string 2', 'string 6', 'string 7',
    'string 8', 'string s', 'string"8', 'string-1', 'stringer',
    '**a!a!**', '2600-2', 'agrebass', 'anteater', 'arp-2600',
    'atypbass', 'axxe', 'barisax', 'bass pad', 'bass syn',
    'bass zzt', 'bass-11', 'bassa', 'bassclar', 'tubular',
    'basse oa', 'bassgtar', 'basshipo', 'basshorn', 'bassviol',
    'bassvox', 'big pik', 'birdland', 'bolubass', 'botbass',
    'bowbass', 'braas', 'bs/strg*', 'uni bass', 'clavbass',
    'boublebs', 'duck 2', 'duckbass', 'earthess', 'elc bass',
    'elec bs*', 'fanknbaz', 'faz bass', 'floorit', 'fret eko',
    'fret not', 'funk baz', 'harmbas5', 'hisbass', 'hotbodom',
    'jan bass', 'jocko', 'jocko 2', 'leedbass', 'lumpbass',
    'minibass', 'mono bs*', 'mooger', 'mooog_b', 'muffel',
    'noisbass', 'octabass', 'orbass', 'ow bass', 'pabass*',
    'pluck-bs', 'polbass1', 'polybass', 'pukbass', 'r + b',
    'ragabass', 'velbass', 'rubber', 'sequbass', 'velgrowl',
    'sincbass', 'wapbass', 'slap 1', 'slap 2', 'slider',
    'slowbass', 'snthbs1*', 'softbass', 'spitbass', 'squisbaz',
    'stand up', 'stbass', 'str.bass', 'strangtk', 'stribass',
    'wet baz', 'stringbz', 'sugita"', 'support', 'swellbaz',
    'swp.bass', 'sybass 2', 'syn bs2*', 'syn bs3*', 'syn bs4*',
    'syncbass', 'taurus', "tenu'ob2", 'wipbass', 'tikbass',
    'ak-48', 'aport', 'ballgame', 'banjo', 'bassdrum',
    'bdth-1', 'bell 1', 'bellike', 'bells', 'bells-gs',
    'bi-plane', 'bottles', 'btmehrdr', 'burst 1', "cascad'4",
    'chimes', 'chimes*', 'chopperz', 'coinop 3', 'copolips',
    'crazyman', 'cricket', 'croztalk', 'db bell', 'didier',
    'dreaming', 'drifter*', 'drumpop', 'dunderz', 'dx-pluck',
    'turbo', 'fallchym', 'fireball', 'flame on', 'flextone',
    'fmpluks', 'furyo 2', 'g.s.2', 'g.s.3', 'glock',
    'winds', 'haunting', 'heart', 'zap', 'horrors',
    'howitzer', 'hvn+hell', 'indian', 'top-gun*', 'insides',
    'jettz 3', 'junkanoo', 'wetfeet', 'kingong', 'kontakte',
    'lctrcute', 'whizz', 'lfo art', 'lfomalet', 'liftoff',
    'loopbell', 'lyle 3 p', "lyles'", 'thundrus', 'machinsm',
    'maniac*', 'marima', 'mofo', 'memories', 'mountain',
    'mrimbah*', 'nasteez', 'warnings', 'noise-dn', 'noisswep*',
    'noizgate', 'nthenews', "nuke em'", 'ociean', 'oceanwav',
    'oozes 3', 'phases*', 'pinwheel', 'pluck', 'polbels2',
    'polnoise', 'portal', 'psychym', 'rainecho', ')rapist(',
    'water', 'rubrtoms', 'saturday', 'scratch', 'seqeunce',
    'sgusting', 'shrnkray', 'simonisk', 'smash*', 'smplthis',
    'papano 4', 'mikpiano', 'honoclab', 'mr.rogrs', 'mtl pno*',
    'musette', 'mutdclv*', 'mutrono', 'nylnpik*', 'nylnpk2*',
    'nylon 12', 'ob8 jump', 'obnoxvox', 'obxa-b5', 'odx 7',
    'oorgan', 'laz harp', 'organ 9', 'organ-1', 'organ-1p',
    'organ-2', 'organism', 'akoustik', 'orgnize*', 'p.organ',
    'p.organ4', 'p.organ5', 'pa ano 5', 'harpo', 'papano 7',
    'lullabox', 'percclav', 'percpno', 'pianitar', 'piano',
    'piano bo', 'pianola', 'b-3.1', 'pinpiano', 'pipeorg.',
    'pipeorg:', 'pipes', 'pipstrng', 'pirates!', 'pno-elec',
    'polpianp', 'prelude1', 'preslez1', 'profit', 'proph w',
    'prophet', 'respiano', 'rmipiano', 'roads', 'sal00n 5',
    'saloon 3', 'b-3.2', 'saloon 7', 'samplorg', 'samsgrnd',
    'sitar i', 'smthsq2*', 'spaniel', 'sprprts*', 'b-3.3',
    'b3+lslie', 'strgtr2*', 'syn clav', 'bells', 'synluth',
    'blabinet', 'synpiano', 'celeste', 'chimes', 'tineout',
    'tonypian', 'toypiano', 'twinstrg', 'church', 'vibechoes',
    'vibes', 'clav b6', 'clavi 2', 'wa clab*', 'clavinet',
    'whaano', 'why fm', 'clickorg', 'wurli8', 'clubs',
    'wurly 2', 'wurly 3', 'x-grand', "xa'organ", 'youreyes',
    'zither', 'cordine1', 'd"ammond', 'greezy1', 'grndr 6*',
]


def patch_name(bank, program):
    """Factory name for bank 0-9, program 0-99."""
    idx = bank * 100 + program
    if 0 <= idx < len(FACTORY_PATCH_NAMES):
        return FACTORY_PATCH_NAMES[idx]
    return ""


BANK_NAMES = [
    "Top 100 (factory)",     # 0
    "Volume 2 (factory)",    # 1
    "Synth #1",              # 2
    "Synth #2",              # 3
    "Woodwinds + Horns",     # 4
    "Horns & Leads",         # 5
    "Strings",               # 6
    "Basses",                # 7
    "FX & Perc",             # 8
    "Keyboards",             # 9
]


def bank_name(bank):
    return BANK_NAMES[bank] if 0 <= bank < len(BANK_NAMES) else ""
